import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/header/Nav";
import Footer from "./components/Footer";
import Providers from "./Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>

          <div className="flex flex-1">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
